name: Linux Build
on:
  push:
    branches:
      - main
      - release
      - release/*
      - feature/*
      - archive/*
  pull_request:
    branches:
      - main
      - release
      - release/*
      - feature/*
      - archive/*

jobs:
  build-ubuntu-gcc-debug:
      uses: ./.github/workflows/cmake-crossplatform.yml
      with:
        os: ubuntu-latest
        c_compiler: gcc
        cpp_compiler: g++
        build_type: Debug

  build-ubuntu-gcc-release:
    needs: build-ubuntu-gcc-debug
    uses: ./.github/workflows/cmake-crossplatform.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cpp_compiler: g++
      build_type: Release

  build-ubuntu-clang-debug:
    uses: ./.github/workflows/cmake-crossplatform.yml
    with:
      os: ubuntu-latest
      c_compiler: clang
      cpp_compiler: clang++
      build_type: Debug

  build-ubuntu-clang-release:
    needs: build-ubuntu-clang-debug
    uses: ./.github/workflows/cmake-crossplatform.yml
    with:
      os: ubuntu-latest
      c_compiler: clang
      cpp_compiler: clang++
      build_type: Release
      
