name: MacOS Build
on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos-matrix-build:
    strategy:
      matrix:
        build_type: [Debug, Release]
        c_compiler: [gcc, clang]
        cxx_compiler: [g++, clang++]

    uses: ./.github/workflows/cmake-crossplatform.yml
    with:
      os: macos-latest
      c_compiler: ${{ matrix.c_compiler }}
      cpp_compiler: ${{ matrix.cxx_compiler }}
      build_type: ${{ matrix.build_type }}
